name: Bandit SAST Scan

on:
  push:
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (JSON report)
        run: |
          bandit -r . -f json -o bandit-report.json -ll

      - name: Get short commit SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report-${{ steps.vars.outputs.short_sha }}
          path: bandit-report.json
